2024-06-12 15:24:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                  
CREATE TABLE USERS (
USERS_ID    INTEGER         AUTO[*] INCREMENT,
MAIL        VARCHAR (100)   NOT NULL,
PASSWORD    VARCHAR (100)   NOT NULL,
GROW_POINT  INTEGER         DEFAULT 0,
LAST_LOGIN_DATE DATE  NOT NULL
PRIMARY KEY (USERS_ID)
)"; 期待されるステートメント "(, FOR, UNSIGNED, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "                  
CREATE TABLE USERS (
USERS_ID    INTEGER         AUTO[*] INCREMENT,
MAIL        VARCHAR (100)   NOT NULL,
PASSWORD    VARCHAR (100)   NOT NULL,
GROW_POINT  INTEGER         DEFAULT 0,
LAST_LOGIN_DATE DATE  NOT NULL
PRIMARY KEY (USERS_ID)
)"; expected "(, FOR, UNSIGNED, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"; SQL statement:
/* usersテーブルの作成 */
create table users (
users_id    integer         auto increment,
mail        varchar (100)   not null,
password    varchar (100)   not null,
grow_point  integer         default 0,
last_login_date date  not null
primary key (users_id)
) [42001-200]
2024-06-12 15:26:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                  
CREATE TABLE USERS (
USERS_ID    INTEGER         AUTO_INCREMENT,
MAIL        VARCHAR (100)   NOT NULL,
PASSWORD    VARCHAR (100)   NOT NULL,
GROW_POINT  INTEGER         DEFAULT 0,
LAST_LOGIN_DATE DATE  NOT NULL
PRIMARY KEY ([*]USERS_ID)
)"; 期待されるステートメント "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "                  
CREATE TABLE USERS (
USERS_ID    INTEGER         AUTO_INCREMENT,
MAIL        VARCHAR (100)   NOT NULL,
PASSWORD    VARCHAR (100)   NOT NULL,
GROW_POINT  INTEGER         DEFAULT 0,
LAST_LOGIN_DATE DATE  NOT NULL
PRIMARY KEY ([*]USERS_ID)
)"; expected "HASH, AUTO_INCREMENT, NOT, NULL, COMMENT, CHECK, REFERENCES, ,, )"; SQL statement:
/* usersテーブルの作成 */
create table users (
users_id    integer         auto_increment,
mail        varchar (100)   not null,
password    varchar (100)   not null,
grow_point  integer         default 0,
last_login_date date  not null
primary key (users_id)
) [42001-200]
2024-06-12 15:33:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                      
CREATE TABLE QUESTIONS (
QUESTIONS_ID	INTEGER		AUTO_INCREMENT,
QUESTION		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
JUDGE		    VARCHAR (10)	NOT NULL DEFAULT[*] ‘回答募集中’,
PRIMARY KEY(QUESTIONS_ID)
FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID)
)"
Syntax error in SQL statement "                      
CREATE TABLE QUESTIONS (
QUESTIONS_ID	INTEGER		AUTO_INCREMENT,
QUESTION		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
JUDGE		    VARCHAR (10)	NOT NULL DEFAULT[*] ‘回答募集中’,
PRIMARY KEY(QUESTIONS_ID)
FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID)
)"; SQL statement:
/* questionsテーブルの作成 */
create table questions (
questions_id	integer		auto_increment,
question		varchar (1000)	not null,
users_id		integer		not null,
judge		    varchar (10)	not null default ‘回答募集中’,
primary key(questions_id)
foreign key (users_id) references users(users_id)
) [42000-200]
2024-06-12 15:33:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                    
CREATE TABLE ANSWERS (
ANSWERS_ID	INTEGER		AUTO_INCREMENT,
QUESTION_ID	INTEGER		NOT NULL,
ANSWER		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
PRIMARY KEY (ANSWERS_ID)
FOREIGN[*] KEY (USERS_ID) REFERENCES USERS(USERS_ID)
)"; 期待されるステートメント "INDEX, ,, )"
Syntax error in SQL statement "                    
CREATE TABLE ANSWERS (
ANSWERS_ID	INTEGER		AUTO_INCREMENT,
QUESTION_ID	INTEGER		NOT NULL,
ANSWER		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
PRIMARY KEY (ANSWERS_ID)
FOREIGN[*] KEY (USERS_ID) REFERENCES USERS(USERS_ID)
)"; expected "INDEX, ,, )"; SQL statement:
/* answersテーブルの作成 */
create table answers (
answers_id	integer		auto_increment,
question_id	integer		not null,
answer		varchar (1000)	not null,
users_id		integer		not null,
primary key (answers_id)
foreign key (users_id) references users(users_id)
) [42001-200]
2024-06-12 15:33:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                     
CREATE TABLE REQUESTS(
    REQUESTS_ID     INTEGER AUTO_INCREMENT,
    ADDRESS_ORDER   VARCHAR (20)    NOT NULL,
    REQUEST         VARCHAR (1000)  NOT NULL,
    USERS_ID        INTEGER         NOT NULL,
    PRIMARY KEY (REQUESTS_ID)
    FOREIGN[*] KEY (USERS_ID) REFERENCES USERS(USERS_ID)
)"; 期待されるステートメント "INDEX, ,, )"
Syntax error in SQL statement "                     
CREATE TABLE REQUESTS(
    REQUESTS_ID     INTEGER AUTO_INCREMENT,
    ADDRESS_ORDER   VARCHAR (20)    NOT NULL,
    REQUEST         VARCHAR (1000)  NOT NULL,
    USERS_ID        INTEGER         NOT NULL,
    PRIMARY KEY (REQUESTS_ID)
    FOREIGN[*] KEY (USERS_ID) REFERENCES USERS(USERS_ID)
)"; expected "INDEX, ,, )"; SQL statement:
/* requestsテーブルの作成 */
create table requests(
    requests_id     integer auto_increment,
    address_order   varchar (20)    not null,
    request         varchar (1000)  not null,
    users_id        integer         not null,
    primary key (requests_id)
    foreign key (users_id) references users(users_id)
) [42001-200]
2024-06-12 15:34:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                      
CREATE TABLE QUESTIONS (
QUESTIONS_ID	INTEGER		AUTO_INCREMENT,
QUESTION		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
JUDGE		    VARCHAR (10)	NOT NULL DEFAULT[*] ‘回答募集中’,
PRIMARY KEY(QUESTIONS_ID)

)"
Syntax error in SQL statement "                      
CREATE TABLE QUESTIONS (
QUESTIONS_ID	INTEGER		AUTO_INCREMENT,
QUESTION		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
JUDGE		    VARCHAR (10)	NOT NULL DEFAULT[*] ‘回答募集中’,
PRIMARY KEY(QUESTIONS_ID)

)"; SQL statement:
/* questionsテーブルの作成 */
create table questions (
questions_id	integer		auto_increment,
question		varchar (1000)	not null,
users_id		integer		not null,
judge		    varchar (10)	not null default ‘回答募集中’,
primary key(questions_id)

) [42000-200]
2024-06-12 15:38:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                      
CREATE TABLE QUESTIONS (
QUESTIONS_ID	INTEGER		AUTO_INCREMENT,
QUESTION		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
JUDGE		    VARCHAR (10)	DEFAULT[*] ‘回答募集中’,
PRIMARY KEY(QUESTIONS_ID)

)"
Syntax error in SQL statement "                      
CREATE TABLE QUESTIONS (
QUESTIONS_ID	INTEGER		AUTO_INCREMENT,
QUESTION		VARCHAR (1000)	NOT NULL,
USERS_ID		INTEGER		NOT NULL,
JUDGE		    VARCHAR (10)	DEFAULT[*] ‘回答募集中’,
PRIMARY KEY(QUESTIONS_ID)

)"; SQL statement:
/* questionsテーブルの作成 */
create table questions (
questions_id	integer		auto_increment,
question		varchar (1000)	not null,
users_id		integer		not null,
judge		    varchar (10)	default ‘回答募集中’,
primary key(questions_id)

) [42000-200]
2024-06-12 15:38:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "ANSWERS" はすでに存在します
Table "ANSWERS" already exists; SQL statement:
/* answersテーブルの作成 */
create table answers (
answers_id	integer		auto_increment,
question_id	integer		not null,
answer		varchar (1000)	not null,
users_id		integer		not null,
primary key (answers_id)

) [42101-200]
2024-06-12 15:38:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUESTS" はすでに存在します
Table "REQUESTS" already exists; SQL statement:
/* requestsテーブルの作成 */
create table requests(
    requests_id     integer auto_increment,
    address_order   varchar (20)    not null,
    request         varchar (1000)  not null,
    users_id        integer         not null,
    primary key (requests_id)
    
) [42101-200]
2024-06-13 11:19:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

) [42001-200]
2024-06-13 11:19:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
) [42001-200]
2024-06-13 11:19:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:19:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:19:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
) [42001-200]
2024-06-13 11:28:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    1,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    1,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    1,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    1,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    1,              /* question_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    1,              /* users_id */
) [42001-200]
2024-06-13 11:28:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    2,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    2,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    2,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    2,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    2,              /* question_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    2,              /* users_id */
) [42001-200]
2024-06-13 11:28:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    3,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    3,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    3,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    3,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    3,              /* question_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    3,              /* users_id */
) [42001-200]
2024-06-13 11:28:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    4,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    4,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    4,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    4,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    4,              /* question_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    4,              /* users_id */
) [42001-200]
2024-06-13 11:28:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    5,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    5,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    5,                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    5,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    5,              /* question_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    5,              /* users_id */
) [42001-200]
2024-06-13 11:29:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    '1',                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    '1',                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    '1',                               
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    '1',                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    '1',              /* question_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    '1',              /* users_id */
) [42001-200]
2024-06-13 11:35:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

) [42001-200]
2024-06-13 11:41:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

) [42001-200]
2024-06-13 11:41:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
) [42001-200]
2024-06-13 11:41:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:41:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:41:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
) [42001-200]
2024-06-13 11:45:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

) [42001-200]
2024-06-13 11:45:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
) [42001-200]
2024-06-13 11:45:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:45:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:45:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
) [42001-200]
<<<<<<< HEAD
2024-06-13 11:54:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '全体',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    1          /* users_id */
) [42102-200]
2024-06-13 11:54:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '経理部',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    2          /* users_id */
) [42102-200]
2024-06-13 11:54:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '総務部',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    3          /* users_id */
) [42102-200]
2024-06-13 11:54:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '人事部',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    4          /* users_id */
) [42102-200]
2024-06-13 11:54:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '全体',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    5          /* users_id */
) [42102-200]
2024-06-13 11:55:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM QUESTIONS REQUESTS ANSWERS[*]"
Syntax error in SQL statement "SELECT * FROM QUESTIONS REQUESTS ANSWERS[*]"; SQL statement:
SELECT * FROM QUESTIONS REQUESTS ANSWERS [42000-200]
=======
2024-06-13 11:49:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                       
INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "                       
INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
/*questionsテーブルテストデータ*/
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    1,
    '回答募集中',

) [42001-200]
2024-06-13 11:49:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    2,
    '解決済み',
    
) [42001-200]
2024-06-13 11:49:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    3,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:49:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    4,
    '回答募集中',
    
) [42001-200]
2024-06-13 11:49:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO QUESTIONS(QUESTIONS_ID,QUESTION,USERS_ID,JUDGE) VALUES(
    NULL,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO questions(questions_id,question,users_id,judge) VALUES(
    null,
    '質問内容ですうううううううううううううううううううううううううううううううううううううううううう',
    5,
    '解決済み',
    
) [42001-200]
>>>>>>> 28b5ba340e9635e16b3e2647561cc5114b8367e3
2024-06-13 15:37:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '全体',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    1,          /* users_id */
) [42102-200]
2024-06-13 15:37:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '経理部',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    2,          /* users_id */
) [42102-200]
2024-06-13 15:37:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '総務部',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    3,          /* users_id */
) [42102-200]
2024-06-13 15:37:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '人事部',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    4,          /* users_id */
) [42102-200]
2024-06-13 15:37:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "REQUEST" が見つかりません
Table "REQUEST" not found; SQL statement:
INSERT INTO request VALUES(
    null,       /*requests_id*/
    '全体',     /* address_order */
    '目安箱の中身ですううううううううううううううう
    ううううううううううううううううううううううう',    /* request */
    5,          /* users_id */
) [42102-200]
2024-06-13 16:36:42 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.RequestsDAO.select(RequestsDAO.java:89)
	at servlet.RListServlet.doGet(RListServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 50 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 44 more
2024-06-13 16:39:11 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.RequestsDAO.select(RequestsDAO.java:89)
	at servlet.RListServlet.doGet(RListServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 50 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 44 more
2024-06-13 16:39:17 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.RequestsDAO.select(RequestsDAO.java:89)
	at servlet.RListServlet.doGet(RListServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 50 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 44 more
2024-06-13 16:44:34 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.RequestsDAO.select(RequestsDAO.java:89)
	at servlet.RListServlet.doGet(RListServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 50 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 44 more
2024-06-13 16:45:56 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.RequestsDAO.select(RequestsDAO.java:89)
	at servlet.RListServlet.doGet(RListServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 50 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 44 more
2024-06-13 16:48:35 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.RequestsDAO.select(RequestsDAO.java:89)
	at servlet.RListServlet.doGet(RListServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 50 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 44 more
2024-06-13 16:48:56 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at dao.RequestsDAO.select(RequestsDAO.java:89)
	at servlet.RListServlet.doGet(RListServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 50 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/pleiades/workspace/D4/data/div.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 44 more
2024-06-14 13:20:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: メソッドはクエリしかサポートしていません。executeQueryのかわりに、excecute、またはexecuteUpdateを使用してください
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
UPDATE Users SET grow_point = grow_point + 1 WHERE users_id=? [90002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:229)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
	at dao.UsersDAO.addPoint(UsersDAO.java:153)
	at servlet.LoginServlet.doPost(LoginServlet.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-06-14 13:35:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: メソッドはクエリしかサポートしていません。executeQueryのかわりに、excecute、またはexecuteUpdateを使用してください
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
UPDATE Users SET grow_point = grow_point + 1 WHERE users_id=? [90002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:229)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
	at dao.UsersDAO.addPoint(UsersDAO.java:153)
	at servlet.LoginServlet.doPost(LoginServlet.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-06-14 13:37:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: メソッドはクエリしかサポートしていません。executeQueryのかわりに、excecute、またはexecuteUpdateを使用してください
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
UPDATE Users SET grow_point = grow_point + 1 WHERE users_id=? [90002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:229)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
	at dao.UsersDAO.addPoint(UsersDAO.java:153)
	at servlet.LoginServlet.doPost(LoginServlet.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-06-14 16:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: メソッドはクエリしかサポートしていません。executeQueryのかわりに、excecute、またはexecuteUpdateを使用してください
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
UPDATE USERS SET last_login_date = current_timestamp WHERE users_id = ? [90002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:229)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
	at dao.UsersDAO.update(UsersDAO.java:328)
	at servlet.LoginServlet.doPost(LoginServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-06-14 16:25:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: メソッドはクエリしかサポートしていません。executeQueryのかわりに、excecute、またはexecuteUpdateを使用してください
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
UPDATE USERS SET last_login_date = current_timestamp WHERE users_id = ? [90002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:229)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
	at dao.UsersDAO.update(UsersDAO.java:328)
	at servlet.LoginServlet.doPost(LoginServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-06-14 16:29:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: メソッドはクエリしかサポートしていません。executeQueryのかわりに、excecute、またはexecuteUpdateを使用してください
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
UPDATE USERS SET last_login_date = current_timestamp WHERE users_id = ? [90002-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.Prepared.query(Prepared.java:229)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
	at dao.UsersDAO.update(UsersDAO.java:328)
	at servlet.LoginServlet.doPost(LoginServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-06-17 11:44:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "                     

INSERT INTO ANSWERS VALUES(
    NULL,                           
    1,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    1,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "                     

INSERT INTO ANSWERS VALUES(
    NULL,                           
    1,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    1,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
/*answersテーブルテストデータ*/

INSERT INTO answers VALUES(
    null,           /* answers_id */
    1,              /* questions_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    1,              /* users_id */
) [42001-200]
2024-06-17 11:44:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    2,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    2,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    2,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    2,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    2,              /* questions_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    2,              /* users_id */
) [42001-200]
2024-06-17 11:44:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    3,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    3,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    3,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    3,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    3,              /* questions_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    3,              /* users_id */
) [42001-200]
2024-06-17 11:44:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    4,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    4,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    4,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    4,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    4,              /* questions_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    4,              /* users_id */
) [42001-200]
2024-06-17 11:44:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO ANSWERS VALUES(
    NULL,                           
    5,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    5,                            
)[*]"; 期待されるステートメント "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "INSERT INTO ANSWERS VALUES(
    NULL,                           
    5,                                
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',              
    5,                            
)[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO answers VALUES(
    null,           /* answers_id */
    5,              /* questions_id */
    '回答ですううううううううううううううううううううううううう
    うううううううううううううううううううううううううううううう',  /* answer */
    5,              /* users_id */
) [42001-200]
